name: Run Tests
on:
  pull_request:
    branches: [develop, main]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.12"
          channel: "stable"

      # Clean Build
      - run: flutter clean

      # Fresh packages
      - run: flutter pub get

      # Test
      - run: flutter test
